appName: X5Plan Blog

server:
  hostname: 127.0.0.1
  port: 5050

database:
  host: 127.0.0.1
  port: 3306
  type: mariadb
  username: root
  password: "123456"
  database: x5plan_blog

redis: redis://127.0.0.1:6379

security:
  sessionSecret: # DO NOT LEAK THIS
  rateLimit:
    enabled: true
    maxRequests: 200
    durationSeconds: 10
  crossOrigin:
    enabled: false
    whitelist: # whitelist is an array and each item must be an url with protocol
      - https://blog.x5plan.club
  recaptcha:
    enabled: false
    secretKey:
    siteKey:
    useRecaptchaNet: false

initialization:
  adminUsername: root
  adminPassword: x5plan-admin
  adminEmail: root@x5plan.club
