name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.0.0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build
